### ISSUE TITLE
[Bug/Error] Crashing during analysis setup?

### ISSUE THREAD

**Issue by Spiteless** [chaosparrot/parrot.py#40]
### Details
Computer: Mac M1
Parrot.py Version: 0.13.0
Python Version: 3.11.1

### Context
I recorded 3 different calssifiers as per [Pokey's instructional video](https://www.youtube.com/watch?v=2j90vhzRoT8), selected train Audio Net, selected my 3 sounds, and during initialization the program crashed.

---

I'll see if I can go through the installation process again and see if I somenhow messed up there.

### Stacktrace

<details>
<summary>Stacktrace</summary>

```
Traceback (most recent call last):
  File "/Users/thiscomputer/src/parrot-test/parrot.py/settings.py", line 47, in <module>
    root_navigation( True )
  File "/Users/thiscomputer/src/parrot-test/parrot.py/settings.py", line 24, in root_navigation
    select_mode()
  File "/Users/thiscomputer/src/parrot-test/parrot.py/settings.py", line 32, in select_mode
    learn_data()
  File "/Users/thiscomputer/src/parrot-test/parrot.py/lib/learn_data.py", line 96, in learn_data
    dataset = AudioDataset( grouped_data_directories, settings )
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thiscomputer/src/parrot-test/parrot.py/lib/audio_dataset.py", line 53, in __init__
    all_samples = load_wav_data_from_srt(listed_files[full_filename], full_filename, self.settings['FEATURE_ENGINEERING_TYPE'], False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thiscomputer/src/parrot-test/parrot.py/lib/wav.py", line 106, in load_wav_data_from_srt
    raw_wav = wf.readframes(frames_to_read * number_channels)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thiscomputer/.pyenv/versions/3.11.1/lib/python3.11/wave.py", line 359, in readframes
    self._data_chunk.seek(pos, 0)
  File "/Users/thiscomputer/.pyenv/versions/3.11.1/lib/python3.11/wave.py", line 156, in seek
    self.file.seek(self.offset + pos, 0)
  File "/Users/thiscomputer/.pyenv/versions/3.11.1/lib/python3.11/wave.py", line 155, in seek
    raise RuntimeError
RuntimeError
/Users/thiscomputer/.pyenv/versions/3.11.1/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

</details>

**Comment by chaosparrot** [comment]
I think this might have to do with some faulty recorded .WAV files, but I can only be sure of that if you can send me the files. Could you contact me on the Talon slack?

**Comment by DamRsn** [comment]
I'm getting the same error. Has it been solved?

The wav files are looking good, however the `*_comparison.wav` files are twice as long as the source ones. I'm not sure if this is expected.

**Comment by DamRsn** [comment]
I recorded a second time and now it seems to work, I don't know what was the problem.

**Comment by John-Keyberg** [comment]
That seems to be the same error that I had. I believe that the error has something to do with pressing backspace during the recording of one of the sounds included. You just have to remove that sound from the training sample for the problem to be resolved.
